FROM flink:1.20
RUN wget -P /opt/flink/lib/ https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.3.0-1.20/flink-sql-connector-kafka-3.3.0-1.20.jar
RUN apt-get update && apt-get install -y python3 python3-pip default-jdk-headless \
    && ln -s /usr/bin/python3 /usr/bin/python \
    && JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) pip3 install apache-flink==1.20.0